version: '3.8'

services:
  azcopy_service:
    build:
      context: .
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
      - SAS_CONTEXT=${SAS_CONTEXT}
      - CONTAINERS=${CONTAINERS}
    volumes:
      - ./export:/export
      - data:/data
    entrypoint: [ "/app/copy.sh" ]
    privileged: true

volumes:
  data: