version: '3.8'

services:
  azcopy_service:
    build:
      context: .
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - AZ_COPY_SOURCE=${AZ_COPY_SOURCE}
      - TENANT_ID=${TENANT_ID}
    volumes:
      - ./data:/data
    entrypoint: [ "/app/copy.sh" ]
